// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string  `json:"id"`
	AuthorID        *string `json:"authorId,omitempty"`
	Body            string  `json:"body"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
	CreatedAt       string  `json:"createdAt"`
	Deleted         bool    `json:"deleted"`
}

type CommentInput struct {
	AuthorID        string  `json:"authorId"`
	Body            string  `json:"body"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID            string    `json:"id"`
	AuthorID      *string   `json:"authorId,omitempty"`
	Title         string    `json:"title"`
	Body          string    `json:"body"`
	AllowComments bool      `json:"allowComments"`
	CommentsID    []*string `json:"commentsId,omitempty"`
	CreatedAt     string    `json:"createdAt"`
	Deleted       bool      `json:"deleted"`
}

type PostInput struct {
	AuthorID string `json:"authorId"`
	Title    string `json:"title"`
	Body     string `json:"body"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	Deleted   bool   `json:"deleted"`
}

type UserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
