package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/k0ch3gar/ozon-task/internal/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, user model.UserInput) (*model.User, error) {
	usr, err := r.us.CreateUser(ctx, user)
	return usr, err
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, postInput model.PostInput) (*model.Post, error) {
	post, err := r.ps.CreatePost(postInput, ctx)
	return post, err
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string) (*string, error) {
	return r.ps.DeletePost(ctx, postID)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, comment model.CommentInput) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CreateComment - createComment"))
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID string) (*string, error) {
	panic(fmt.Errorf("not implemented: DeleteComment - deleteComment"))
}

func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*model.User, error) {
	return r.us.DeleteUser(ctx, userID)
}

func (r *mutationResolver) UpdatePostTitle(ctx context.Context, postID string, title string) (*model.Post, error) {
	return r.ps.UpdatePostTitle(ctx, postID, title)
}

func (r *mutationResolver) UpdatePostBody(ctx context.Context, postID string, body string) (*model.Post, error) {
	return r.ps.UpdatePostBody(ctx, postID, body)
}

func (r *mutationResolver) UpdatePostCommentsAllowance(ctx context.Context, postID string, allow *bool) (*model.Post, error) {
	if allow == nil {
		return nil, nil
	}

	return r.ps.UpdatePostCommentsAllowance(ctx, postID, *allow)
}

func (r *mutationResolver) UpdateCommentBody(ctx context.Context, commentID string, body string) (*model.Comment, error) {
	//TODO implement me
	panic("implement me")
}

// ListPosts is the resolver for the listPosts field.
func (r *queryResolver) ListPosts(ctx context.Context, page int32) ([]*model.Post, error) {
	post, err := r.ps.GetPostsByPage(uint64(page), ctx)
	return post, err
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, postID string) (*model.Post, error) {
	post, err := r.ps.GetPostByid(postID, ctx)
	return post, err
}

// PostComments is the resolver for the postComments field.
func (r *queryResolver) PostComments(ctx context.Context, postID string) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: PostComments - postComments"))
}

// ChildComments is the resolver for the childComments field.
func (r *queryResolver) ChildComments(ctx context.Context, commentID string) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: ChildComments - childComments"))
}

func (r *queryResolver) UserByID(ctx context.Context, userID string) (*model.User, error) {
	usr, err := r.us.GetUserById(ctx, userID)
	return usr, err
}

func (r *queryResolver) UserByName(ctx context.Context, username string) (*model.User, error) {
	usr, err := r.us.GetUserByName(ctx, username)
	return usr, err
}

// CommentCreated is the resolver for the commentCreated field.
func (r *subscriptionResolver) CommentCreated(ctx context.Context) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentCreated - commentCreated"))
}

// CommentUpdated is the resolver for the commentUpdated field.
func (r *subscriptionResolver) CommentUpdated(ctx context.Context) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentUpdated - commentUpdated"))
}

// CommentDeleted is the resolver for the commentDeleted field.
func (r *subscriptionResolver) CommentDeleted(ctx context.Context) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentDeleted - commentDeleted"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }

type queryResolver struct{ *Resolver }

type subscriptionResolver struct{ *Resolver }
